### ISSUE TITLE
Accessing SynthSegCSVD Docker - Assistance Requested

### ISSUE THREAD

**Issue by whtuye** [AICONSlab/SynthSegCSVD#2]
Dear SynthSegCSVD Developer Team,

I hope this message finds you well. Firstly, I would like to extend my heartfelt congratulations to you and your team for the development of SynthSegCSVD. It's an impressive accomplishment, and your willingness to share it on GitHub for the benefit of the wider community is greatly appreciated.

Our team has been eager to experiment with SynthSegCSVD, recognizing its potential to significantly enhance our projects. However, we've encountered an issue that we hope you could assist us with. We attempted to download the Docker container from the provided link: [https://s3.us-east.cloud-object-storage.appdomain.cloud//cloud-synthsegcsvdrc05/rc06.tar.gz](https://s3.us-east.cloud-object-storage.appdomain.cloud//cloud-synthsegcsvdrc05/rc06.tar.gz), but unfortunately, it appears that the file is not accessible.

We have made several attempts to download it, considering various potential issues on our end, but it seems that the problem might be with the link or the storage access permissions. We were wondering if this is a known issue and if there might be an alternative link or solution you could provide to help us access the Docker container.

Your work on SynthSegCSVD is incredibly valuable to the community, and we are keen to explore its capabilities further. Any assistance you could provide in resolving this download issue would be deeply appreciated.

Looking forward to your response, and thank you once again for your contribution to the field and your support in this matter.

Best regards,

Ye Tu
whtuye@163.com
Department of Anesthesiology, Tongji Hospital, Tongji Medical College, Huazhong University of Science and Technology, Wuhan, China.

**Comment by eag** [comment]
Thank you for your interest in this tool. Please find the current version and download links here: https://github.com/AICONSlab/segcsvd

Best,
Erin

**Comment by dvannederpelt** [comment]
Dear Erin,

The link (https://github.com/AICONSlab/segcsvd) doesn't seem to work. Is there another possiblity to download this?
Many thanks!

Best regards,
David

**Comment by eag** [comment]
Hi David,

We are currently preparing the initial release version and will update the link as soon as it is ready. We apologize for any inconvenience.

Best, 
Erin
